version: '3.8'
services:
  data-persistence:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - '3001:3000'
    volumes:
      - data-volume:/data

volumes:
  data-volume:
