version: '3.8'
services:
  memory-hog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    deploy:
      resources:
        limits:
          memory: 500M # Ograniczenie pamięci
    restart: always
