version: '3'
services:
  memory-hog:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - '3003:3000'
    deploy:
      resources:
        limits:
          memory: 100M
