version: '3'
services:
  cpu-hog:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - '3000:3000'
    deploy:
      resources:
        limits:
          cpus: '0.5'
