version: '3.8'
services:
  cpu-hog:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - '3000:3000'
    deploy:
      resources:
        limits:
          cpus: '0.5' # 50% mocy jednego rdzenia
