version: '3.8'
services:
  resource-limiter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3005:3000'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
