version: '3.8'
services:
  high-disk-io:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3002:3000'
    deploy:
      resources:
        limits:
          blkio_config:
            weight: 500 # Ograniczenie prędkości zapisu/odczytu (wartość od 10 do 1000)
    restart: always
    volumes:
      - ./data:/app/data # Wolumin do zapisywania danych
